module.exports = {
  apps: [
    {
      name: 'ssh-web-next',
      script: 'node_modules/next/dist/bin/next',
      args: 'start',
      cwd: './',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        NEXT_PORT: 3000,
        WEBSOCKET_PORT: 8081,
        NEXT_PUBLIC_WEBSOCKET_HOST: 'localhost',
        NEXT_PUBLIC_WEBSOCKET_PORT: '8081',
        DIRECTORY_POLLING_INTERVAL: 2000,
      },
      error_file: './logs/next-error.log',
      out_file: './logs/next-out.log',
      log_file: './logs/next-combined.log',
      time: true,
      merge_logs: true,
      pre_deploy_local: 'npm run build',
    },
    {
      name: 'ssh-web-websocket',
      script: 'tsx',
      args: 'lib/ssh-server-standalone.ts',
      cwd: './',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'production',
        WEBSOCKET_PORT: 8081,
        DIRECTORY_POLLING_INTERVAL: 2000,
      },
      error_file: './logs/websocket-error.log',
      out_file: './logs/websocket-out.log',
      log_file: './logs/websocket-combined.log',
      time: true,
      merge_logs: true,
    },
  ],
};
